/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AbstractSimplexControlador;
import controlador.SimplexControlador;
import java.util.ArrayList;
import modelo.AbstractSolucionadorSimplex;
import modelo.DtoSimplex;
import modelo.SolucionadorSimplex;
import modelo.parser.IParser;
import modelo.parser.Parser;

/**
 *
 * @author fm010
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private boolean fraccionario;
    private boolean gomory;
    private boolean solucionDirecta; 
    AbstractSimplexControlador controlador;
    
    public PantallaPrincipal() {
        this.solucionDirecta = false;
        this.fraccionario = true;
        this.gomory = true;
        this.controlador = new SimplexControlador();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        grupoFormato = new javax.swing.ButtonGroup();
        grupoSolucion = new javax.swing.ButtonGroup();
        grupoPasos = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        botonSimplex = new javax.swing.JButton();
        botonSolucionEntera = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        labelFormato = new javax.swing.JLabel();
        radioFraccion = new javax.swing.JRadioButton();
        radioDecimal = new javax.swing.JRadioButton();
        labelEntero = new javax.swing.JLabel();
        radioGomory = new javax.swing.JRadioButton();
        radioBB = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        radioMostrarPasos = new javax.swing.JRadioButton();
        radioSolucionDirecta = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        areaTexto.setColumns(12);
        areaTexto.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        areaTexto.setRows(5);
        areaTexto.setTabSize(4);
        areaTexto.setText("(0) max z = 15 x1 + 10 x2\n(1)            x1          <= 2\n(2)                    x2  <= 3\n(3)            x1 +    x2   = 4");
        areaTexto.setToolTipText("");
        areaTexto.setWrapStyleWord(true);
        areaTexto.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(areaTexto);

        botonSimplex.setText("Simplex");
        botonSimplex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimplexActionPerformed(evt);
            }
        });

        botonSolucionEntera.setLabel("Solucion Entera");

        botonBorrar.setLabel("Borrar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonSimplex)
                        .addGap(18, 18, 18)
                        .addComponent(botonSolucionEntera)
                        .addGap(18, 18, 18)
                        .addComponent(botonBorrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSimplex)
                    .addComponent(botonSolucionEntera)
                    .addComponent(botonBorrar))
                .addGap(25, 25, 25))
        );

        labelFormato.setText("Formato Numérico");

        grupoFormato.add(radioFraccion);
        radioFraccion.setSelected(true);
        radioFraccion.setText("Fracción");
        radioFraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFraccionActionPerformed(evt);
            }
        });

        grupoFormato.add(radioDecimal);
        radioDecimal.setText("Decimal");
        radioDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDecimalActionPerformed(evt);
            }
        });

        labelEntero.setText("Solucion Entera");

        grupoSolucion.add(radioGomory);
        radioGomory.setSelected(true);
        radioGomory.setText("Cortes de Gomory");
        radioGomory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGomoryActionPerformed(evt);
            }
        });

        grupoSolucion.add(radioBB);
        radioBB.setText("Branch and Bound");
        radioBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBBActionPerformed(evt);
            }
        });

        jLabel1.setText("Pasos Intermedios");

        grupoPasos.add(radioMostrarPasos);
        radioMostrarPasos.setSelected(true);
        radioMostrarPasos.setText("Mostrar Pasos");
        radioMostrarPasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMostrarPasosActionPerformed(evt);
            }
        });

        grupoPasos.add(radioSolucionDirecta);
        radioSolucionDirecta.setText("Solucion Directa");
        radioSolucionDirecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSolucionDirectaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFormato)
                    .addComponent(labelEntero)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioFraccion)
                            .addComponent(radioDecimal)
                            .addComponent(radioGomory)
                            .addComponent(radioBB)
                            .addComponent(radioMostrarPasos)
                            .addComponent(radioSolucionDirecta))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelFormato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioFraccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioDecimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEntero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioGomory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioMostrarPasos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSolucionDirecta)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioFraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFraccionActionPerformed
        fraccionario = true;
    }//GEN-LAST:event_radioFraccionActionPerformed

    private void radioDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDecimalActionPerformed
        fraccionario = false;
    }//GEN-LAST:event_radioDecimalActionPerformed

    private void radioGomoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGomoryActionPerformed
        gomory = true;
    }//GEN-LAST:event_radioGomoryActionPerformed

    private void radioBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBBActionPerformed
        gomory = false;
    }//GEN-LAST:event_radioBBActionPerformed

    private void radioMostrarPasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMostrarPasosActionPerformed
        solucionDirecta = false;
    }//GEN-LAST:event_radioMostrarPasosActionPerformed

    private void radioSolucionDirectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSolucionDirectaActionPerformed
        solucionDirecta = true;
    }//GEN-LAST:event_radioSolucionDirectaActionPerformed

    private void botonSimplexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimplexActionPerformed
        if (solucionDirecta) {
            controlador.setVista(new PantallaPasoIntermedio(controlador));
            controlador.solucionarSimplex(areaTexto.getText());
            this.dispose();
        }else {
            controlador.setVista(new PantallaPasoIntermedio(controlador));
            controlador.siguientePasoSimplex(areaTexto.getText());
            this.dispose();
        }
    }//GEN-LAST:event_botonSimplexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       /* IParser parser = new Parser();
        DtoSimplex res = parser.parse("(0) max z = 15 x1 + 10 x2\n" +
"(1)            x1         <= 2\n" +
"(2)                    x2 <= 3\n" +
"(3)            x1 +    x2  = 4");
        System.out.println(res);
        
        res.setVariablesBasicas();
        AbstractSolucionadorSimplex s = new SolucionadorSimplex();
        res = s.completarProblema(res);
        ArrayList<DtoSimplex> r = s.solucionar(res);
        int t = r.size()-1;
        System.out.println("factible: "+r.get(t).esFactible());
        System.out.println("acotado: "+r.get(t).esAcotado());*/
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonSimplex;
    private javax.swing.JButton botonSolucionEntera;
    private javax.swing.ButtonGroup grupoFormato;
    private javax.swing.ButtonGroup grupoPasos;
    private javax.swing.ButtonGroup grupoSolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEntero;
    private javax.swing.JLabel labelFormato;
    private javax.swing.JRadioButton radioBB;
    private javax.swing.JRadioButton radioDecimal;
    private javax.swing.JRadioButton radioFraccion;
    private javax.swing.JRadioButton radioGomory;
    private javax.swing.JRadioButton radioMostrarPasos;
    private javax.swing.JRadioButton radioSolucionDirecta;
    // End of variables declaration//GEN-END:variables
}
